
define i32 @main() {
entry:

	%a = alloca i32
	%0 = add i32 0, 0				; expr_pop
	store i32 %0, i32* %a			; int variable assignment (variable.rs)

	%b = alloca i32
	%1 = add i32 0, 0				; expr_pop
	store i32 %1, i32* %b			; int variable assignment (variable.rs)

	br label %cond2

cond2:
	%a_0 = load i32, i32* %a 			 ; LlvmLoad load_i32
	%2 = icmp ult i32 %a_0, 5
;depth: 2
	%3 = add i1 %2, 0				; expr_pop
	br i1 %3, label %body2, label %exit2

body2:
	%a_1 = load i32, i32* %a 			 ; LlvmLoad load_i32
	%4 = add i32 %a_1, 0				; expr_pop
	call void @print_i32(i32 %4)

	%a_2 = load i32, i32* %a 			 ; LlvmLoad load_i32
	%6 = add i32 %a_2, 1
	%7 = add i32 %6, 0				; expr_pop
	store i32 %6, i32* %a		 ; set symbol (symbol.rs)

	br label %cond8

cond8:
	%b_0 = load i32, i32* %b 			 ; LlvmLoad load_i32
	%8 = icmp ult i32 %b_0, 5
;depth: 8
	%9 = add i1 %8, 0				; expr_pop
	br i1 %9, label %body8, label %exit8

body8:
	%b_1 = load i32, i32* %b 			 ; LlvmLoad load_i32
	%10 = add i32 %b_1, 0				; expr_pop
	call void @print_i32(i32 %10)

	%b_2 = load i32, i32* %b 			 ; LlvmLoad load_i32
	%12 = add i32 %b_2, 1
	%13 = add i32 %12, 0				; expr_pop
	store i32 %12, i32* %b		 ; set symbol (symbol.rs)

	br label %cond8

exit8:
	%14 = add i32 0, 0				; expr_pop
	store i32 0, i32* %b		 ; set symbol (symbol.rs)

;	; pushing a new string on the stack ..."yup"
	%15 = getelementptr inbounds [4 x i8], [4 x i8]* @str0, i32 0, i32 0 ; llvm_retrieve_static_string		;LLVM Register for String @ ExprCount 15(variable.rs) 				; Printing a string type (expr_pop - register increment by LlvmTempRegister)
	call i32 (i8*, ...) @printf(i8* %15)											; Auto generated by LlvmCallPrint (print.rs)

	br label %cond2

exit2:

	ret i32 0 ; llvm_main_close
}

;String Constants
@str0 = private unnamed_addr constant [5 x i8] c"yup\0A\00", align 1


@fmt = private constant [4 x i8] c"%d\0A\00"
declare i32 @printf(i8*, ...)
define void @print_i32(i32 %value) {
    %fmt_ptr = getelementptr [4 x i8], [4 x i8]* @fmt, i32 0, i32 0
    call i32 (i8*, ...) @printf(i8* %fmt_ptr, i32 %value)
    ret void
}
define void @print_i1(i1 %b) {
entry:
    ; Format string to print "true" or "false"
    %true_str = alloca [6 x i8], align 1
    %false_str = alloca [7 x i8], align 1

    ; Store the strings "true" and "false" in memory
    store [6 x i8] c"true\0A\00", [6 x i8]* %true_str, align 1
    store [7 x i8] c"false\0A\00", [7 x i8]* %false_str, align 1

    ; Compare the boolean value (%b) to true (1)
    %is_true = icmp eq i1 %b, true

    ; If %b is true, print "true", otherwise print "false"
    br i1 %is_true, label %print_true, label %print_false

print_true:
    ; Call printf with "true" string
    %true_ptr = getelementptr inbounds [6 x i8], [6 x i8]* %true_str, i32 0, i32 0
    call i32 @printf(i8* %true_ptr)
    br label %done

print_false:
    ; Call printf with "false" string
    %false_ptr = getelementptr inbounds [7 x i8], [7 x i8]* %false_str, i32 0, i32 0
    call i32 @printf(i8* %false_ptr)
    br label %done

done:
    ret void
}