declare i32 @printf(i8*, ...)
define void @print_i1(i1 %b) {
entry:
    ; Format string to print "true" or "false"
    %true_str = alloca [6 x i8], align 1
    %false_str = alloca [7 x i8], align 1

    ; Store the strings "true" and "false" in memory
    store [6 x i8] c"true\0A\00", [6 x i8]* %true_str, align 1
    store [7 x i8] c"false\0A\00", [7 x i8]* %false_str, align 1

    ; Compare the boolean value (%b) to true (1)
    %is_true = icmp eq i1 %b, true

    ; If %b is true, print "true", otherwise print "false"
    br i1 %is_true, label %print_true, label %print_false

print_true:
    ; Call printf with "true" string
    %true_ptr = getelementptr inbounds [6 x i8], [6 x i8]* %true_str, i32 0, i32 0
    call i32 @printf(i8* %true_ptr)
    br label %done

print_false:
    ; Call printf with "false" string
    %false_ptr = getelementptr inbounds [7 x i8], [7 x i8]* %false_str, i32 0, i32 0
    call i32 @printf(i8* %false_ptr)
    br label %done

done:
    ret void
}
@fmt = private constant [4 x i8] c"%d\0A\00"

define void @print_i32(i32 %value) {
    %fmt_ptr = getelementptr [4 x i8], [4 x i8]* @fmt, i32 0, i32 0
    call i32 (i8*, ...) @printf(i8* %fmt_ptr, i32 %value)
    ret void
}

define i32 @main(){
entry:
%0 = icmp ult i32 69, 420
%1 = add i1 %0, 0

br i1 %1, label %then0, label %else0
then0:

%2 = add i32 1, 0

call void @print_i32(i32 %2)
%4 = getelementptr inbounds [5 x i8], [5 x i8]* @str0, i32 0, i32 0
;LLVM Register for String @ ExprCount 4(variable.rs)

call i32 (i8*, ...) @printf(i8* %4)
; Auto generated by LlvmCallPrint (print.rs)
br label %end
else0:

%7 = getelementptr inbounds [6 x i8], [6 x i8]* @str1, i32 0, i32 0
;LLVM Register for String @ ExprCount 7(variable.rs)

call i32 (i8*, ...) @printf(i8* %7)
; Auto generated by LlvmCallPrint (print.rs)
%10 = getelementptr inbounds [7 x i8], [7 x i8]* @str2, i32 0, i32 0
;LLVM Register for String @ ExprCount 10(variable.rs)

call i32 (i8*, ...) @printf(i8* %10)
; Auto generated by LlvmCallPrint (print.rs)
br label %end

end:

ret i32 0
}
@str1 = private unnamed_addr constant [7 x i8] c"ayooo\0A\00", align 1
@str0 = private unnamed_addr constant [6 x i8] c"breh\0A\00", align 1
@str2 = private unnamed_addr constant [8 x i8] c"yughhh\0A\00", align 1
