use crate::parser::expression::expr::{DataType, Expression};
use crate::parser::expression::expression::expression;
use crate::parser::parser::{AstNode, Parser};
use crate::{llvm::llvm_print::llvm_call_print_local, scanner::token::TokenType};
use crate::parser::declaration::declaration::{Statement, Declaration};
use std::fmt;

pub fn print_statement(parser: &mut Parser) {
    expression(parser);
    let expr_ast = parser.ast_stack.pop();
    if let Some(ast_node) = expr_ast { 

        let stmt = Statement::new_print_statement(ast_node.unpack_expression());
        println!("{stmt}");
    }
    
    let (expr, top) = parser.expr_pop();
    match &expr.data_type {
        DataType::Boolean(_) => parser.emit_instruction(&LlvmCallPrint::Integer(top).print_i1()),
        DataType::Integer(_) => parser.emit_instruction(&LlvmCallPrint::Integer(top).print_i32()),
        DataType::String (_) => parser.emit_instruction(&LlvmCallPrint::String(top).call_print())
    }
    parser.expr_count += 1;
    parser.consume(TokenType::Semicolon, "Expect semicolon after value");
}

pub enum LlvmCallPrint {
    String(u32), //register value
    Integer(u32),
}
impl LlvmCallPrint {
    pub fn call_print(&self) -> String {
        match self {
            Self::String(register) => format!("\tcall i32 (i8*, ...) @printf(i8* %{})\t\t\t\t\t\t\t\t\t\t\t; Auto generated by LlvmCallPrint (print.rs)\n", register),
            Self::Integer(_) => panic!()
        }
    }
    pub fn print_i32(&self) -> String {
        match self {
            Self::Integer(register) => llvm_call_print_local(register.clone(), "i32"),
            _ => panic!("Not a i32")
        }
    }
    pub fn print_i1(&self) -> String {
        match self {
            Self::Integer(register) => llvm_call_print_local(register.clone(), "i1"),
            _ => panic!("Not a i32")
        }
    }
}